// Generated by rosidl_generator_cs from handyman_msgs/msg/HandymanMsg.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace handyman_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class HandymanMsg : RosMessage
			{
				public string message;
				public string detail;


				public HandymanMsg()
				{
					this.message = "";
					this.detail = "";
				}

				public HandymanMsg(string message, string detail)
				{
					this.message = message;
					this.detail = detail;
				}

				new public static string GetMessageType()
				{
					return "handyman_msgs/msg/HandymanMsg";
				}

			} // class HandymanMsg
		} // namespace msg
	} // namespace handyman_msgs
} // namespace SIGVerse.RosBridge
